config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[edit update show destory]
  def index
    @flats = Flat.all
  end

  def show
  end
  def new
    @flat = Flat.new
  end
  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    @flat.update
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end
  def destroy
    @flat.destroy
  end
  private
  def flat_params
    params.require(:flat).permit(%i[name address])
  end
  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="navbar">
  <h2>Simple Airbnb</h2>
  <%= link_to "Add Flat", new_flat_path , class:"btn btn-primary" %>
</div>

<div class="container">
  <% @flats.each do |flat| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.address %></p>
        <%= flat.number_of_guests %> <%= flat.price_per_night %>
      </div>
    </div>
  <% end  %>
</div>
<i class="fas fa-user-friends"></i>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>